### ISSUE TITLE
Provide `endpoint-url` option

### ISSUE THREAD

**Issue by dan-online** [MassivDash/S3_Manager#12]
I love the tool, however I need the ability to set the endpoint-url to a different URL. This is both not possible in either config file in the `~/.aws` folder, would it be possible to integrate into the app, or at least provide an argument I could pass with endpoint-url (I'm using linux so that's possible)

Thanks,
Dan

**Comment by MassivDash** [comment]
As far as I've seen the official aws rust sdk docs, it may be possible to add a window with manual / custom configuration. Unfortunately right now I don't have time to implement this feature.

**Comment by dan-online** [comment]
Hey @MassivDash, I noticed this was closed, was the issue resolved? I can't really tell from the pull requests

**Comment by MassivDash** [comment]
Hello, yes I exposed system env to the program, you can alter the program by setting a custom env

**Comment by dan-online** [comment]
Thanks! It works a treat, however I did notice upon reviewing the code that I had to set `S3_CUSTOM_ENDPOINT=1` *and* `S3_CUSTOM_ENDPOINT_URL=<url>`

However, it works great and thank you for the release :tada:

**Comment by MassivDash** [comment]
Thanks, totally forgot, Ill update the docs with the second env. Happy S3 management
