### ISSUE TITLE
`cargo tauri dev` results in "error: no such subcommand: `tauri`"

### ISSUE THREAD

**Issue by cosimo** [MassivDash/S3_Manager#15]
I'm trying to follow the instructions but I'm stuck right at the very beginning.
Also, when I try `cargo run` in the `src-tauri` directory, which I'm not sure it's what I'm supposed to do, but I tried anyway, a desktop/GTK application is started (?), saying `index.html not found`.

When I run `npm install` and `npm run dev` for the js app, something starts on port 3000, but when I load it up in the browser, I get this message `window.__IPC_TAURI__` error...

Any guidance?

**Comment by MassivDash** [comment]
Hello, in order to run dev mode on the app you need follow these
- https://tauri.app/v1/guides/getting-started/prerequisites 
- Install tauri-cli ```cargo install tauri-cli```
- Run the project from rust by ```cargo tauri dev``` from the root of the project

I'll improve the docs.
