### ISSUE TITLE
Application Fails to Open After Snap Installation on Ubuntu 22.04

### ISSUE THREAD

**Issue by kuttim** [MassivDash/S3_Manager#28]
I installed the "S3_Manager" application via Snap Store on my Ubuntu 22.04 (amd64) system. However, the application refuses to open. It just won't launch.

As a workaround, I tried installing it using `sudo dpkg -i s3-manager_0.9.3_amd64.deb`. But when I ran the `s3-manager` command afterwards in the terminal, I received the following error:

`s3-manager: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

It seems that the application is missing the necessary `libssl.so.1.1` shared library.

Upon closer examination of the logs, I discovered that the error I encountered while attempting to execute the s3-manager directly from the terminal coincided with the timestamp when I initially ran the application, which was installed using the snap store.
 ```
cat /var/log/syslog | grep -i "s3-manager"
Jun 26 18:50:03 mikk s3-manager.desktop[41367]: s3-manager: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
Would it be possible to include the necessary shared library in future builds? This would ensure compatibility and proper functioning of the application.

System Information (not sure if it's needed as it should affect every user without the required library):

- Operating System: Ubuntu 22.04 (amd64)
- Installation Method: Snap Store
- Application Version: 0.9.3

Thanks!

**Comment by MassivDash** [comment]
Thanks for bringing this issue up, I was able to replicate and fix the problem. The previous releases were build upon ubuntu 20, ubuntu 22 bumped the openSSL version and got rid of all old packages. 

the following release has ubuntu 20 and 22 images and debs packages, I have tested the ubuntu 22 locally, it should work fine. 

gonna close the issues.

**Comment by MassivDash** [comment]
https://github.com/MassivDash/S3_Manager/releases/tag/app-v0.9.5
