### ISSUE TITLE
Multipart upload support?

### ISSUE THREAD

**Issue by zenomeki** [MassivDash/S3_Manager#37]
Hey!

Thanks for this app! Serves as a great example on how to use the S3 SDK as well as being a useful shortcut utility to manage our buckets contents 😄 

Do you plan on supporting multipart uploads? The `PutObject` often fails with large (800 MB+) files, and it would even help with the speed factor as well...

**Comment by MassivDash** [comment]
Hello, thanks for letting me know that the big file uploads fail, I will look into solving that error, maybe read the file and if big enough choose the multi upload call. 

Can you tell me what system you are using ? I did some intial testing with big files like >1gb movies on Mac OS, and did not notice the problem.

**Comment by zenomeki** [comment]
Windows mostly (which may complicate things) and we also noticed that there's an upload speed drop when dealing larger files.
Our region is `eu-west-2` which might also be a factor.

**Comment by zenomeki** [comment]
👍 Thanks!

**Comment by MassivDash** [comment]
@zenomeki Please free to reopen the issue if your uploads start to fail, thx.
