### ISSUE TITLE
Support for s3-compatible object storage

### ISSUE THREAD

**Issue by osmboy** [MassivDash/S3_Manager#47]

**Comment by MassivDash** [comment]
Could you extrapolate a bit more on what this issue is about ?

**Comment by osmboy** [comment]
os: macos 13.4 
the same config,s3cmd works :
```shell
s3cmd ls -c ~/.s3cfg.tebi
2023-10-28 02:20  s3://tebi0boy
```
but `s3manager`:
<img width="1238" alt="image" src="https://github.com/MassivDash/S3_Manager/assets/20849756/0c86e33c-383c-435b-b621-f0aafaf88882">


s3manager config :
```shell
cat ~/.aws/credentials
aws_access_key_id=<testak>
aws_secret_access_key=<testkey>
cat ~/.aws/config
[default]
region=us-west-1
output=json
```

system env of custom s3 endpoint  that has been  launchctl load 
```shell
cat /Library/LaunchDaemons/custom.s3.endpoint.plist | grep ENDPOINT
        <string>launchctl setenv S3_CUSTOM_ENDPOINT 1</string>
        <string>launchctl setenv S3_CUSTOM_ENDPOINT_URL https://s3.usw.tebi.io</string>
 ```
 s3 manager version:
 [S3.Manager_0.9.6_x64.dmg](https://github.com/MassivDash/S3_Manager/releases/download/app-v0.9.6/S3.Manager_0.9.6_x64.dmg)
        
Is it possible that s3manager does not support s3-compatible object storage ?

**Comment by MassivDash** [comment]
The application is build on top of AWS S3 Rust official package, I do not think it will be compatible with non aws services, but I could be wrong, I do not have any s3 clones services available, in order to find out what is the actual error, you might need to run the app in dev mode, and investigate yourself.
